- site: Facebook
  name: Stuart P. Bentley
  url: http://facebook.com/stuartpb

- site: Twitter
  name: stuartpb
  url: https://twitter.com/stuartpb

- site: GitHub
  name: stuartpb
  url: https://github.com/stuartpb

- site: LinkedIn
  name: stuartpb
  url: http://linkedin.com/in/stuartpb

- site: Stack Overflow
  name: Stuart P. Bentley
  url: http://stackoverflow.com/users/34799/stuart-p-bentley

- site: Coderbits
  name: spb
  url: https://coderbits.com/spb

- site: about.me
  name: stuartpb
  url: http://about.me/stuartpb

- site: Foursquare
  name: stuartpb
  url: https://foursquare.com/stuartpb

- site: PlugMap
  name: stuartpb
  url: http://plugmap.com/user/stuartpb

- site: Cloud9
  name: stuartpb
  url: http://c9.io/stuartpb

- site: YouTube
  name: YOUsTUBEntley
  url: http://www.youtube.com/user/YOUsTUBEntley

- site: Wikipedia
  name: Stuart P. Bentley
  url: http://en.wikipedia.org/wiki/User:Stuart_P._Bentley

- site: Gittip
  name: stuartpb
  url: https://www.gittip.com/stuartpb/

- site: Bountysource
  name: stuartpb
  url: https://www.bountysource.com/#users/17953-stuartpb

- site: Flattr
  name: stuartpb
  url: https://flattr.com/profile/stuartpb

- site: Thingiverse
  name: stuartpb
  url: http://www.thingiverse.com/stuartpb

- site: Wikia
  name: Stuart P. Bentley
  url: http://www.wikia.com/wiki/User:Stuart_P._Bentley

- site: Google+
  name: Stuart Bentley
  url: https://plus.google.com/117089477951137457045

- site: CodePen
  name: spb
  url: http://codepen.io/spb

- site: Coderwall
  name: stuartpb
  url: https://coderwall.com/stuartpb

- site: Seattle Public Library
  name: stuartpb
  url: http://seattle.bibliocommons.com/collection/show/94601702_stuartpb/library/completed

- site: Geeklist
  name: stuartpb
  url: https://geekli.st/stuartpb

- site: Launchpad
  name: stuart
  url: http://launchpad.net/~stuart

- site: Hacker News
  name: spb
  url: http://news.ycombinator.com/user?id=spb

- site: Userscripts.org
  name: stuart
  url: http://userscripts.org/users/stuart

- site: Scribbls
  name: STUART
  url: http://www.scribbls.com/users/STUART-2608

- site: Ohloh
  name: stuartpb
  url: https://www.ohloh.net/accounts/stuartpb

- site: Canvas
  name: stuartpb
  url: http://canv.as/user/stuartpb

- site: Steam
  name: stuart
  url: http://steamcommunity.com/id/stuart

- site: Steam Forums
  name: STUART
  url: http://forums.steampowered.com/forums/member.php?u=514292

- site: Xbox Live
  name: Snacman
  url: https://live.xbox.com/Profile?gamertag=Snacman

- site: Rosetta Code
  name: Stuart P. Bentley
  url: http://rosettacode.org/wiki/User:Stuart_P._Bentley

- site: Fitocracy
  name: stuartpb
  url: http://www.fitocracy.com/profile/stuartpb/

- site: OkCupid
  name: stuartpb
  url: http://okcupid.com/profile/stuartpb

- site: GetGlue
  name: stuartpb
  url: http://getglue.com/stuartpb

- site: Ward's Wiki
  name: StuartPbBentley
  url: http://c2.com/cgi/wiki?StuartPbBentley

- site: GIMP Plugin Registry
  name: spb
  url: http://registry.gimp.org/user/43911

- site: Freesound
  name: Stuart P. Bentley
  url: http://freesound.org/people/Stuart%20P.%20Bentley/

- site: TV Tropes
  name: STUART
  url: http://tvtropes.org/pmwiki/pmwiki.php/Tropers/STUART

- site: Bulbapedia
  name: Stuart P. Bentley
  url: http://bulbapedia.bulbagarden.net/wiki/User:Stuart_P._Bentley

- site: Telltale Games Forums
  name: Stuart P. Bentley
  url: http://www.telltalegames.com/forums/member.php?u=46636

- site: Arch Linux Forums
  name: STUART
  url: https://bbs.archlinux.org/profile.php?id=40320

- site: TF2Maps.net
  name: StuartPB
  url: http://forums.tf2maps.net/member.php?u=6518

- site: Runic Games
  name: STUART
  url: http://forums.runicgames.com/memberlist.php?mode=viewprofile&u=14297
